platform :ios, '9.0'
target "RZBluetoothExample" do
    pod 'RZBluetooth', :path => "../"
end

target "RZBluetoothExampleUITests" do
    pod 'RZBluetooth/Mock', :path => "../"
    pod 'RZBluetooth/Test', :path => "../"
end
