platform :ios, '9.0'
target "RZBluetoothExample" do
    pod 'RZBluetooth', :path => "../"
end

target "RZBluetoothExampleUITests" do
    pod 'RZBluetooth', :path => "../"
    pod 'RZBluetooth/Mock', :path => "../"
    pod 'RZBluetoothTest', :path => "../"
end

target "RZBluetoothExampleTests" do
    pod 'RZBluetooth', :path => "../"
    pod 'RZBluetooth/Mock', :path => "../"
    pod 'RZBluetoothTest', :path => "../"
end
