platform :ios, '8.1'

target "RZBluetoothExample" do
    pod 'RZBluetooth', :path => "../"
end

target "RZBluetoothExampleUITests" do
    pod 'RZBluetooth', :path => "../"
    pod 'RZBluetooth/Mock', :path => "../"
    pod 'RZBluetooth/Test', :path => "../"
end
